llh:
  method: poisson

injected_params:
  astro_norm: 1.44
  gamma_astro: 2.37
  prompt_norm: 1.0
  conv_norm: 1.0
  CR_grad: 0.0
  delta_gamma: 0.0
  barr_h: 0.0
  barr_w: 0.0
  barr_y: 0.0
  barr_z: 0.0

hists:
  method: bkde
  bandwidth: 0.0006
  bins_low: 0
  bins_up: 1
  bins_number: 1650


weights:
  method: nnm_fit
  main_config: /home/saturn/capn/capn105h/software/BESTIE/src/BESTIE/configs/NNM/main_SPL.cfg
  analysis_config: /home/saturn/capn/capn105h/software/BESTIE/src/BESTIE/configs/NNM/analysis_configs/asimov_SPL.yaml
  override_configs: 
  config_dir: /home/saturn/capn/capn105h/software/BESTIE/src/BESTIE/configs/NNM


network:
  framework: jax
  input_size: 14
  hidden_layers:
    - layer: Dense
      size: 14
      activation: relu
    - layer: Dense
      size: 28
      activation: relu
    - layer: Dense
      size: 28
      activation: relu
    - layer: Dense
      size: 52
      activation: relu
    - layer: Dense
      size: 52
      activation: relu
    - layer: Dense
      size: 104
      activation: relu
    - layer: Dense
      size: 104
      activation: relu
    - layer: Dense
      size: 1
      activation: lin
loss:
  method: fisher
  optimality: a
  signal_idx: [0,1]

training:
  lr:
    lr: 0.3
    method: cos
  batch_size: 50000
  optimizer: sgd
  epochs: 300

rng: 187

dataset_config: /home/saturn/capn/capn105h/software/BESTIE/src/BESTIE/configs/dataset.yaml

dataset_path: /home/saturn/capn/capn105h/data/IceCube/simulation/torch_datasets/dataset_baselineMSU.pt
sample_weights_path: /home/saturn/capn/capn105h/data/IceCube/simulation/torch_datasets/bin_sample_weights_MSU.pt
