llh:
  method: poisson

injected_params:
  astro_norm: 1.44
  gamma_astro_first: 1.31
  gamma_astro_second: 2.74
  prompt_norm: 1.0
  conv_norm: 1.0
  CR_grad: 0.0
  delta_gamma: 0.0
  barr_h: 0.0
  barr_w: 0.0
  barr_y: 0.0
  barr_z: 0.0

hists:
  method: bkde
  bandwidth: 0.001
  bins_low: 0
  bins_up: 1
  bins_number: 1650


weights:
  method: nnm_fit
  main_config: /home/saturn/capn/capn105h/software/BESTIE/src/BESTIE/configs/NNM/main_BPL.cfg
  analysis_config: /home/saturn/capn/capn105h/software/BESTIE/src/BESTIE/configs/NNM/analysis_configs/asimov_BPL.yaml
  override_configs: 
  config_dir: /home/saturn/capn/capn105h/software/BESTIE/src/BESTIE/configs/NNM


network:
  framework: jax
  input_size: 14
  hidden_layers:
    - layer: Dense
      size: 850
      activation: relu
    - layer: Dense
      size: 1650
      activation: relu
    - layer: Dense
      size: 3300
      activation: relu
    - layer: Dense
      size: 3300
      activation: relu
    - layer: Dense
      size: 6600
      activation: relu
    - layer: Dense
      size: 1
      activation: lin
loss:
  method: fisher
  optimality: a
  signal_idx: [0,1,2]

training:
  lr:
    lr: 0.0003
    method: cos
  batch_size: 5000
  optimizer: sgd
  epochs: 25

rng: 1871

dataset_path: /home/saturn/capn/capn105h/data/IceCube/simulation/torch_datasets/dataset_baselineMSU.pt
sample_weights_path: /home/saturn/capn/capn105h/data/IceCube/simulation/torch_datasets/bin_sample_weights_MSU.pt
