# !replace with your own dataframe path!
dataframe: /home/saturn/capn/capn105h/data/IceCube/simulation/NNMFit_dataframes/toy_sources_0.5deg_200_sources.parquet

input_vars:
  - var_name: energy_truncated
    scale: log
    transform: sphere
  - var_name: zenith_MPEFit
    scale: cos
    transform: sphere
  - var_name: azimuth_MPEFit
    transform: sphere
  - var_name: ra_MPEFit
    transform: sphere
  - var_name: L5_sigma_paraboloid
    scale: log
    transform: sphere

# list of other input vars that can be used (if available in your dataframe):
  # - var_name: L5_bayes_llh_diff
  #   transform: sphere
  # - var_name: L5_cog_rho
  #   transform: sphere
  # - var_name: L5_cog_z
  #   transform: sphere
  # - var_name: L5_lseparation
  #   transform: sphere
  # - var_name: L5_nch
  #   scale: log10
  #   transform: sphere
  # - var_name: L5_ndir_c
  #   transform: sphere
  # - var_name: L5_rlogl
  #   transform: sphere
  # - var_name: L5_sdir_e
  #   transform: sphere
  # - var_name: L5_sigma_paraboloid
  #   scale: log10
  #   transform: sphere
  # - var_name: BDTScore
  #   transform: sphere
  # - var_name: BDTCascScore
  #   transform: sphere
    
fourier_feature_mapping:
  method: none
  mapping_size: 128
  scale: 1.

exists_vars:
  - reco_dir_exists
  - energy_truncated_exists

# cut the input vars so it covers the same range as the standard binning
cut_vars:
  - var_name: energy_truncated
    min: 100
    max: 10000000
  - var_name: zenith_MPEFit
    min: 1.483485438
    max: 3.141592654

# adapt depending on your configured flux (in the NNMFit configs)
flux_vars:
  - MCPrimaryEnergy
  - powerlaw
  - mceq_conv_H4a_SIBYLL23c
  - mceq_conv_GST4_SIBYLL23c
  - mceq_pr_H4a_SIBYLL23c
  - mceq_pr_GST4_SIBYLL23c
  - barr_h_mceq_H4a_SIBYLL23c
  - barr_w_mceq_H4a_SIBYLL23c
  - barr_z_mceq_H4a_SIBYLL23c
  - barr_y_mceq_H4a_SIBYLL23c
