dataframe: /home/saturn/capn/capn105h/data/IceCube/simulation/NNMFit_dataframes/dataset_baselineMSU.parquet

input_vars:
  - var_name: energy_truncated
    scale: log10
    standardize: True
  - var_name: zenith_MPEFit
    scale: cos
    standardize: True
  - var_name: azimuth_MPEFit
    standardize: True 
  - var_name: L5_bayes_llh_diff
    standardize: True 
  - var_name: L5_cog_rho
    standardize: True 
  - var_name: L5_cog_z
    standardize: True 
  - var_name: L5_lseparation
    standardize: True 
  - var_name: L5_nch
    scale: log10
    standardize: True 
  - var_name: L5_ndir_c
    standardize: True 
  - var_name: L5_rlogl
    standardize: True 
  - var_name: l5_sdir_e
    standardize: True 
  - var_name: L5_sigma_paraboloid
    scale: log10
    standardize: True 
  - var_name: BDTScore
    standardize: False 
  - var_name: BDTCascScore
    standardize: False

exists_vars:
  - reco_dir_exists
  - energy_truncated_exists

cut_vars:
  - var_name: energy_truncated
    min: 100
    max: 10000000
  - var_name: zenith_MPEFit
    min: 1.483485438
    max: 3.141592654

flux_vars:
  - MCPrimaryEnergy
  - powerlaw
  - mceq_conv_H4a_SIBYLL23c
  - mceq_conv_GST4_SIBYLL23c
  - mceq_pr_H4a_SIBYLL23c
  - mceq_pr_GST4_SIBYLL23c
  - barr_h_mceq_H4a_SIBYLL23c
  - barr_w_mceq_H4a_SIBYLL23c
  - barr_z_mceq_H4a_SIBYLL23c
  - barr_y_mceq_H4a_SIBYLL23c

sample_weights:
  method: bin
  vars:
    - energy_truncated
    - ...

