llh:
  method: poisson

injected_params:
  galactic_norm: 1.0
  toy_source_norm: 2.0
  astro_norm: 1.44
  gamma_astro: 2.37
  prompt_norm: 1.0
  conv_norm: 1.0
  CR_grad: 0.0
  delta_gamma: 0.0
  barr_h: 0.0
  barr_w: 0.0
  barr_y: 0.0
  barr_z: 0.0

hists:
  method: bkde
  bandwidth: 0.01
  bins_low: 0
  bins_up: 1
  bins_number: 3300


weights:
  method: nnm_fit
  main_config: /home/saturn/capn/capn105h/software/BESTIE/src/BESTIE/configs/NNM/main_SPL_cringe.cfg
  analysis_config: /home/saturn/capn/capn105h/software/BESTIE/src/BESTIE/configs/NNM/analysis_configs/asimov_SPL.yaml
  override_configs: 
  config_dir: /home/saturn/capn/capn105h/software/BESTIE/src/BESTIE/configs/NNM


network:
  framework: jax
  #input_size: 14 input size should be deprecrated
  hidden_layers:
    - layer: Dense
      size: 1024
      activation: relu
    - layer: Dense
      size: 1024
      activation: relu
    - layer: Dense
      size: 2048
      activation: relu
    - layer: Dense
      size: 1
      activation: sigmoid
loss:
  method: fisher
  fisher_method: jacobian
  optimality: ellipsoid
  signal_idx: [0,1]

training:
  lr:
    lr: 0.001
    method: cos
  batch_size: 50000
  batches_per_epoch: 100
  optimizer: adam
  epochs: 500
  resets: 10
  average_gradients: True
  train_number_of_bins: False

rng: 187

transformation:
  method: none